### ISSUE TITLE
Neopixel LEDs über RGBW-Werte

### ISSUE THREAD

**Issue by MKleinSB** [knotechgmbh/Callibot#2]
Liebes knotech-Team,
aus meiner (und didaktischer) Sicht wäre es sinnvoll, die RGB-LEDs gleich zu behandeln. Die Onboard-LED und die des Maqueen sollten also ähnliche Blöcke besitzen.
![Unbenannt](https://user-images.githubusercontent.com/37311672/56904105-e8397480-6a9d-11e9-8421-6a7bd33386bd.png)
Zudem kann man bei Eurer Lösung keine fließenden Übergänge zwischen den Farben programmieren.
Zusammengehörige Blöcke würde ich über  //% weight
sortieren. Also Liniensensor zu Liniensensor usw. und die Fernsteuerblöcke in ein Untermenü auslagern.
Nur so als Idee

**Comment by MKleinSB** [comment]
Und die Entfernung bitte bitte in cm. Das mit den mm kapiert mein Grundkurs in Klasse 8 zum Teil noch nicht.
Hinter warte bis .... fehlt die Einheit (cm!), also am besten wegen der Auswahlmöglichkeit 
Entfernung (cm) <=> XX
Bei der Temperatur ist die Einheit ja ogisch für die Schüler.

**Comment by knotechgmbh** [comment]
Hallo MKleinSB,
bei den RGB-LEDs wollten wir die Programmierung so einfachst wie möglich halten, deshalb die Beschränkung auf wenige Grundfarben. Da die Ansteuerung in der Adapterplatine geschieht, ist eine Änderung nicht mehr so einfach möglich.
Die Sortierung der Blöcke ist durchaus so gewollt, und weil das Projekt so überschaubar ist, haben wir keine Gewichtung über %weight vorgenommen sondern den Code "sortiert". Wir werden weitere Rückmeldungen prüfen und ggf. die Reihenfolge ändern.
Die Untermenüs hatten wir uns angeschaut, es erschien uns aber in anbetracht der wenigen Befehle nicht hilfreich, die Befehle nochmal in Untermenüs zu packen. Auch hier warten wir weiteres Feedback ab und werden Vorschläge prüfen.
Das mit den mm überraschte nun doch (bei den Wartezeiten wird immerhin mit ms gearbeitet), wir haben zwischenzeitlich eine Auswahlmöglichkeit mm/cm geschaffen.
Für weitere Vorschläge sind wir natürlich jederzeit offen

**Comment by MKleinSB** [comment]
Vielen Dank für die Überarbeitungen!
ms kennen die Schüler schon aus dem "normalen" Wartebefehl von Makecode.
