### ISSUE TITLE
Keine Funktionen mit Umlauten, Hilfe fehlt usw.

### ISSUE THREAD

**Issue by MKleinSB** [knotechgmbh/Callibot#3]
Wohl eher ein Fehler in MakeCode: Wenn man in Javascript arbeitet und zurück auf die Blockdarstellung geht, werden die Umlaute falsch dargestellt.
Also besser statt ä ae usw. verwenden.
![Unbenannt](https://user-images.githubusercontent.com/37311672/57199019-64d6c200-6f7a-11e9-8f7b-b5e499f27371.png)

Außerdem fehlt die Beschreibung der Funktionen wenn man mit der Maus darübergeht. Einige Werte sollten sinnvoll vobelegt sein, bzw. der Bereich vorgegeben.

**Comment by knotechgmbh** [comment]
Hallo MKleinSB,
das mit den Umlauten ist suboptimal, aber ae/ue sieht auch nicht sehr schön aus... Wir sind da noch am Prüfen, was machbar ist.
Bei den mouseover-Hilfen ist es teilweise schwierig, etwas sinnvolles zu schreiben - weil die Funktion sich eigentlich von selbst erklärt. Hinweise für die Wertebereiche der Parameter sind sinnvoll, das schauen wir uns an.
Bei den Werten sind Wertebereiche vorgegeben, wenn man z.B. beim Motor den %-Wert anklickt, öffnet sich ein verschiebbarer Balken.
