### ISSUE TITLE
Paket kann in Makecode nicht mehr eingeladen werden

### ISSUE THREAD

**Issue by MKleinSB** [knotechgmbh/Callibot#4]
Leider lässt sich das Paket nicht mehr in MakeCode einladen. Version erhöhen?

Brauche ich für die Servos ein update oder werden die nicht an P1 und P2 aufgesteckt? Bei mir zucken sie nur rum,

**Comment by knotechgmbh** [comment]
Update:
Nochmal neu hochgeladen, nun passen die Release-Nummern zwar nicht mehr - aber das Paket lässt sich runterladen.  Scheinbar hatte sich da etwas verhakt (?)
